### ISSUE TITLE
Invalid regex group on Firefox

### ISSUE THREAD

**Issue by OrsoBruno96** [Nevenall/remark-containers#1]
I'm using this package within `react-markdown`.
Everything works well on Chrome, but on Firefox (60.8.0) I get the following error message in console:

```
SyntaxError: invalid regexp group
```

And the incriminated regex is the following:
```javascript
/^:::[\t\f ]*(?<type>\S+)[\t\f ]*(?<options>.*?)$/m
```

which is at the beginning of `index.js` of this repo.

I can try to investigate the reason why Firefox doesn't like this regex, but for the moment all my application crashes due to this regex.

**Comment by OrsoBruno96** [comment]
I found the reason.
[Named group regex](https://stackoverflow.com/questions/5367369/named-capturing-groups-in-javascript-regex) is an ES2018 feature and it seems that not all browsers (in particular old browsers) support it, for example, Firefox 60.8.0 and Edge.

Firefox is seeing `(?<type>\S+)` as a negative lookahead because of the `?<`, but this feature is not supported in JS (as far as I know), so it crashes.

I will submit a PR soon with a patch.

**Comment by Nevenall** [comment]
Thanks so much!
I'll get that merged in
