### ISSUE TITLE
Using HTML elements as types with transformation to custom element raises error

### ISSUE THREAD

**Issue by calaoa** [Nevenall/remark-containers#10]
When trying to transform a standard HTML element into a custom element (e.g. transforming `table` into `tableau`), an error is raised as if remark was interpreting the original element while one would expect the new one instead, wouldn't we?

Custom configuration example:
```
.use(containers, {
    default: true,
    custom: [
        {
        type: "table",
        element: "tableau",
        noparse: true,
        transform: function(node, config, tokenize) {
          console.log("table", node);
          node.children[0].type = "code";
        }
      }]
```

Live example (with copied source code of `remark-containers` in order to get around #7  in the browser): https://codesandbox.io/s/remark-containers-rbk9x

Would you say it's a misconfiguration or a bug?

Cheers

**Comment by Nevenall** [comment]
`type` is the keyword to look for in the Markdown. `element` is the html element to output. 

I think your issue is `type: "table"` because it's already defined in Remark.

Try this
https://codesandbox.io/s/remark-containers-587u3?file=/src/index.js

**Comment by calaoa** [comment]
Thank you Neveall, you're right indeed, I mistook the element for an HTML one while it's a Remark one at this stage. This means remark-containers won't work with `::: table` right? Should this be considered as a bug? Do you know which other types might be forbidden since already defined in Remark?

**Comment by Nevenall** [comment]
`::: table` should only fail if it's defined as a custom container. 
We could probably check for name collisions in custom containers so technically a bug. 
Not sure if there is a list of parser names documented anywhere, but we could get it from debugging.

**Comment by calaoa** [comment]
I thought as well that `::: table` would fail only as a custom container, but unless I'm mistaken it does even without it, am I wrong? Here's an example, it seems (same sandbox URL as above, but with the custom configuration commented out): https://codesandbox.io/s/remark-containers-rbk9x
