### ISSUE TITLE
Issue when using nested containers in combination with remark-attr

### ISSUE THREAD

**Issue by calaoa** [Nevenall/remark-containers#11]
## Steps to reproduce

Using the input below in combination with [remark-attrs](https://github.com/arobase-che/remark-attr) by @arobase-che:

```
::: div
::: div
_Buster_{class="icon"}

Keaton
:::
:::
```

## Result

```
<div>
<div>
<p>
<em>Buster</em>{class="icon"}</p>
<p>Keaton</p>
</div>
</div>
```

However, removing `Keaton` produces the expected output: `<em class="icon">Buster</em>`. Not sure if the issue relates to `remark-containers` or to `remark-attr`, any suggestion welcome. 

## Code to reproduce

https://codesandbox.io/s/remark-containers-rbk9x?file=/src/index.js

**Comment by Nevenall** [comment]
That's interesting. It looks to be a strange interaction of containers and attrs. 

```
::: div

*Buster*{class="icon"}
:::
``` 

Works just fine, but if, for any reason, there's more than 1 line between the attr and the `::: div` it doesn't. 

```
::: div


*Buster*{class="icon"}
:::
``` 
Doesn't work and neither does 

::: div
a|b|c
-|-|-
1|2|3
*Buster*{class="icon"}
:::

It might be a markdown parsing rule around * or _, I'm not sure.

**Comment by arobase-che** [comment]
Interesting !

I can't take a look at it right now. I think this weekend I will have some time to study it carefully. 

Thanks for the mention.

**Comment by arobase-che** [comment]
I'm sorry, I never looked at this issue again.
I think I should archive remark-attr because I never update it for the new version of `remark`.
And I don't think I will have the time to do it any time soon.

**Comment by Nevenall** [comment]
I haven't updated my plugin either :)
