### ISSUE TITLE
Ability to process other node attributes than "class"

### ISSUE THREAD

**Issue by calaoa** [Nevenall/remark-containers#12]
This issue is about proposing the support of the following transformation natively for any node, using the standard [attribute selector syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors):

Input:

```
::: div class-one class-two [id="id-1"] [name="name-1"]
:::
```
Output:

```
<div class="class-one class-two" id="id-1' name="name-1">
</div>
```

This could be useful in particular for generating forms using, but not only. What do you think? (I have a pull request at hand, just waiting for possible other syntax options)

**Comment by Nevenall** [comment]
That's a cool idea, but I don't think I'd integrate it directly into the containers plugin. What about a custom container configuration you could import and use?

**Comment by calaoa** [comment]
Thanks for your feedback Nevenall. A custom configuration could make it as well indeed. I understand how to apply custom configurations to specific elements, but I'm not sure if there's a way to apply one to any element by default, is this something that is possible at the moment?

**Comment by Nevenall** [comment]
You bet! Thanks for being interested! 
There is no way right now to apply to custom config to any element. I think for that it would be easier to fix the interaction with remark-attrs, then, I think, we could do the same things with that module.

**Comment by calaoa** [comment]
You're right, `remark-attrs` could actually be used indeed, I had overlooked that, however as a user I tend to prefer having the ability to declare all element attributes from a common location, when using a container... By the way I would actually use the following syntax (no brackets):

```
::: div class-one class-two id="id-1" name="name-1"
:::
```

**Comment by calaoa** [comment]
Would it be meaningful to add a field in the options that would contain a function handling the conversion of the config to the node properties? That way, the developer could provide a custom config-to-attributes converter, what do you think? 

I have a working implementation proposal at [@babouk/remark-containers](https://github.com/babouk/remark-containers/blob/other-attributes/src/index.js), so I could easily submit a pull request in case you consider it's relevant.
