### ISSUE TITLE
remark@next (13)

### ISSUE THREAD

**Issue by wooorm** [Nevenall/remark-containers#13]
Hi!

remark is switching to a new parser (and compiler) internally ([`remarkjs/remark#536`](https://github.com/remarkjs/remark/pull/536)), which will break this plugin.
I will create a generic directives plugin though, time permitting, in this month, which would be a good inspiration for fenced divs.
Keep an eye out that plugin, which will also have [micromark](https://github.com/micromark/micromark#list-of-extensions) and [mdast](https://github.com/syntax-tree/mdast-util-from-markdown#list-of-extensions) extensions too, and feel free to ask me questions!

**Comment by max-pod** [comment]
> 
> 
> Hi!
> 
> remark is switching to a new parser (and compiler) internally ([`remarkjs/remark#536`](https://github.com/remarkjs/remark/pull/536)), which will break this plugin.
> I will create a generic directives plugin though, time permitting, in this month, which would be a good inspiration for fenced divs.
> Keep an eye out that plugin, which will also have [micromark](https://github.com/micromark/micromark#list-of-extensions) and [mdast](https://github.com/syntax-tree/mdast-util-from-markdown#list-of-extensions) extensions too, and feel free to ask me questions!

Hi!
I use case where I would kill for that plugin. Do you have any idea where that plugin is in the dev phase?

**Comment by Nevenall** [comment]
Hello!

I definitely intend to update my remark plugins soonish. Hopefully within a month or two.

**Comment by wooorm** [comment]
@podolsk-maxi I’m working on it now

**Comment by wooorm** [comment]
I have created a micromark extension for my interpretation of the generic directive syntax: https://github.com/micromark/micromark-extension-directive
And a corresponding utility for mdast: https://github.com/syntax-tree/mdast-util-directive
And wrapped ’em all up in: https://github.com/remarkjs/remark-directive

I hope those serve as inspiration: note that you don’t have to split them up in several repos, but that’s how I like to work.

Finally, something like `remark-containers` can be done with `remark-directive` too, where `remark-directive` handles the syntax and tree, and `remark-containers` changes the tree?

**Comment by Nevenall** [comment]
Perfect, thank you!

**Comment by Neo-Desktop** [comment]
Hi, is this still broken? I was just wondering because this would be amazing in my current project.

Keep up the amazing work!

**Comment by wooorm** [comment]
No, but see the mention of remark-directives, which does similar things

**Comment by Neo-Desktop** [comment]
thank you for the prompt reply, I appreciate it

**Comment by Nevenall** [comment]
thanks!

Stay tuned, I've started working on the update.
________________________________
