### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'blockTokenizers' of undefined

### ISSUE THREAD

**Issue by ivands** [Nevenall/remark-containers#14]
After adding this plugin I start getting the following error:
```UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'blockTokenizers' of undefined```

Example:
```
import { remark }	from 'remark'
import html		from 'remark-html'
import containers	from 'remark-containers'

var result = await remark()
  .use(html)
  .use(containers)
  .process(content);
```

**Comment by Nevenall** [comment]
Are you using Remark 13.0.0 or higher? 
This plugin uses the old parser architecture and isn't compatible with any recent version of Remark. 
There is a new plugin called remark-directives that has similar features.
