### ISSUE TITLE
Ability to configure the containers which should not be parsed

### ISSUE THREAD

**Issue by calaoa** [Nevenall/remark-containers#6]
Following up on #4, this issue is about adding the ability to configure the containers whose content should not be parsed, e.g. as follows:

```
.use(containers, {
  default: true, 
  custom: [{
    element: 'hero',
    parse: false
   }]
})
```

This would alleviate entering `noparse` for each target container. What do you think?

**Comment by Nevenall** [comment]
Looks good! Thanks for the pull request
