### ISSUE TITLE
Usage of named groups in regex raises an issue with some browsers

### ISSUE THREAD

**Issue by calaoa** [Nevenall/remark-containers#7]
The regex used to identify and parse containers (copied below) is using named groups to identify the `noparse`, `type` and `config` values. While named groups improve code readability, it seems they introduce an issue with some browsers including recent ones such as Firefox 77, which have not yet implemented named groups yet (ECMAScript 2018 as far as I understand). 

This issue is about discussing the replacement of named groups by numbered groups (as it was before) so as to ease browser support.

* Current regex:  `/^:::[\t\f ]*(?<noparse>noparse)?[\t\f ]*(?<type>\S+)[\t\f ]*(?<config>.*?)$/m`
* New regex proposal: `/^:::[\t\f ]*(noparse)?[\t\f ]*(\S+)[\t\f ]*(.*?)$/m`

**Comment by Nevenall** [comment]
It's true! I was leaning into the fact that Firefox 78 supports named groups as of June 29, and the logic gets fiddly without them. 
When I get the chance I'll look into doing it without named grouped.
